# Generated by Django 4.2.6 on 2023-10-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_producto_stock_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_anterior',
        ),
    ]
