# Generated by Django 4.2.6 on 2023-10-25 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_producto_stock_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Rut')),
                ('razon_social', models.CharField(max_length=120, verbose_name='Razón Social')),
                ('contacto', models.IntegerField(blank=True, null=True, verbose_name='Número de contacto')),
                ('pagina_web', models.CharField(blank=True, null=True, verbose_name='Página web')),
                ('correo_prov', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='fecha de ingreso')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('cantidad_compra', models.IntegerField(verbose_name=' Cantidad comprada')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.producto', verbose_name='Producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Conformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conformidad', models.CharField(choices=[('1', 'Conforme'), ('2', 'No conforme')], max_length=1, verbose_name='Tipo de Conformidad')),
                ('obs_prov', models.TextField(blank=True, null=True, verbose_name='Causa')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Conformidad',
                'verbose_name_plural': 'Conformidades',
                'ordering': ['id'],
            },
        ),
    ]
