# Generated by Django 4.2.6 on 2023-10-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_proveedor_ordencompra_conformidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
    ]
