# Generated by Django 4.2.6 on 2023-10-26 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_proveedor_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['id'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='cantidad_compra',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='pro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='DetOc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.ordencompra')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.producto')),
            ],
            options={
                'verbose_name': 'Detalle de oc',
                'verbose_name_plural': 'Detalles oc',
                'ordering': ['id'],
            },
        ),
    ]
