# Generated by Django 4.2.6 on 2023-10-26 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedor'),
        ),
    ]
