# Generated by Django 4.2.6 on 2023-10-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_ordencompra_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformidad',
            name='tipo_conformidad',
            field=models.CharField(choices=[('Conforme', 'Conforme'), ('No conforme', 'No conforme')], verbose_name='Tipo de Conformidad'),
        ),
    ]
