# Generated by Django 5.1 on 2024-08-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_conformidad_tipo_conformidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAbrazadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCruceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='identificador único')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('obss', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=True, verbose_name='Incorporado')),
                ('tipo_abrazadera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoabrazadera', verbose_name='Tipo de abrazadera')),
                ('tipo_cruceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipocruceta', verbose_name='Tipo de cruceta')),
                ('tipo_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoposte', verbose_name='Tipo de poste')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['id'],
            },
        ),
    ]
