# Generated by Django 5.1 on 2024-08-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_poste_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='obss',
            new_name='obs',
        ),
        migrations.AddField(
            model_name='poste',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='poste',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
