# Generated by Django 5.1 on 2024-08-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_rename_obss_poste_obs_poste_latitud_poste_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='estado',
        ),
        migrations.AddField(
            model_name='poste',
            name='remate',
            field=models.BooleanField(default=False, verbose_name='¿Tiene remate?'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='tipo_abrazadera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoabrazadera', verbose_name='Transformador'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='tipo_cruceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipocruceta', verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='tipo_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoposte', verbose_name='Tipo Poste'),
        ),
    ]
