# Generated by Django 5.1 on 2024-09-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_rename_tipoproducto_proyecto_remove_producto_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
