# Generated by Django 5.1 on 2024-09-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_proyecto_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='contacto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo'),
        ),
    ]
