# Generated by Django 5.1 on 2024-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_proveedor_proyecto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proveedor',
            field=models.ManyToManyField(blank=True, to='erp.proveedor', verbose_name='Proveedores'),
        ),
    ]
