# Generated by Django 5.1 on 2024-10-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_remove_proyecto_proveedor_proyecto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cant_casas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de casas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cant_departamentos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de departamentos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='shaft',
            field=models.BooleanField(default=False, verbose_name='¿shaft?'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='soti',
            field=models.BooleanField(default=False, verbose_name='¿Sala soti?'),
        ),
    ]
