# Generated by Django 5.1 on 2024-10-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_diseno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseno',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='diseno',
            name='pproyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.proyecto', verbose_name='proyecto'),
        ),
    ]
