# Generated by Django 5.1 on 2024-10-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_remove_diseno_proveedor_diseno_pproyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseno',
            old_name='pproyecto',
            new_name='proyecto',
        ),
    ]
