# Generated by Django 5.1 on 2024-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_rename_pproyecto_diseno_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseno',
            name='hp',
            field=models.TextField(blank=True, null=True, verbose_name='HP'),
        ),
    ]
