# Generated by Django 5.1 on 2024-10-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_diseno_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusión'),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='HP'),
        ),
    ]
