# Generated by Django 5.1 on 2024-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_alter_diseno_odf_alter_diseno_odf1_alter_diseno_odf2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='sp16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuantos splitter de 16'),
        ),
        migrations.AddField(
            model_name='diseno',
            name='sp8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuantos splitter de 8'),
        ),
    ]
