# Generated by Django 5.1 on 2024-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_diseno_sp16_diseno_sp8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='desc',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='adm',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='m1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Mufa M1'),
        ),
        migrations.AlterField(
            model_name='diseno',
            name='m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Mufa M2'),
        ),
    ]
