# Generated by Django 5.1 on 2024-10-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_diseno_cable12_diseno_cable24_diseno_cable4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('Potencia', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Potencia')),
                ('obs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('proyecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.proyecto', verbose_name='proyecto')),
            ],
        ),
    ]
