# Generated by Django 5.1 on 2024-10-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_potencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potencia',
            name='Potencia',
        ),
        migrations.AlterField(
            model_name='potencia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('mufa', 'Mufa'), ('nap', 'NAP')], max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='potencia',
            name='potencia',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia'),
        ),
    ]
