# Generated by Django 5.1 on 2024-11-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_remove_potencia_potencia_alter_potencia_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='sp2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuantos splitter de 2'),
        ),
        migrations.AddField(
            model_name='diseno',
            name='sp4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuantos splitter de 4'),
        ),
    ]
