# Generated by Django 5.1 on 2024-11-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_diseno_sp2_diseno_sp4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='tipo_abrazadera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoabrazadera', verbose_name='Abrazadera'),
        ),
    ]
