# Generated by Django 5.1 on 2024-11-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_alter_poste_tipo_abrazadera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='tipo_cruceta',
        ),
        migrations.AddField(
            model_name='poste',
            name='transformador',
            field=models.BooleanField(default=False, verbose_name='¿Tiene transformador?'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='tipo_abrazadera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipoabrazadera', verbose_name='Altura'),
        ),
        migrations.DeleteModel(
            name='TipoCruceta',
        ),
    ]
